name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DigitalOcean Container Registry
      uses: docker/login-action@v2
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          registry.digitalocean.com/ggtips/ggtips-frontend:latest
          registry.digitalocean.com/ggtips/ggtips-frontend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        
    - name: Deploy to DigitalOcean Droplet
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        script: |
          # Pull latest image
          docker pull registry.digitalocean.com/ggtips/ggtips-frontend:latest
          
          # Stop and remove old container
          docker stop ggtips-frontend || true
          docker rm ggtips-frontend || true
          
          # Run new container
          docker run -d \
            --name ggtips-frontend \
            --restart unless-stopped \
            -p 80:80 \
            -p 443:443 \
            registry.digitalocean.com/ggtips/ggtips-frontend:latest
          
          # Clean up old images
          docker image prune -f
